imports:
    - { resource: "@OperaAdminBundle/Resources/config/easy_admin.yaml" }
    - { resource: "@OperaTaxonomyBundle/Resources/config/easy_admin.yaml" }

easy_admin:
    design:
        assets:
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'
        menu:
            - { label: 'Layout', children: ['Page'] }
            - { label: 'Content', children: ['Article', { label: 'Medias', route: 'opera_admin_media_list' }] }
            - { label: 'Taxonomy', children: ['Tag'] }

    entities:
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - title
                    - slug
                    - { property: body, type: FOS\CKEditorBundle\Form\Type\CKEditorType }
                    - tags
